In [ ]:
# we use mean, median and mode to fill the null values

In [ ]:
#                                                                  LIST COMPREHENSION

In [ ]:
# list comprehension using for loop

#  variable = [ operation loop if_condition]
#  variable = [ operation if_condition else_statement loop ]

In [ ]:
# To find the square of only the even numbers
# list_number = [1,2,3,4,5,6,7,8,9,10]
list_number= list(range(50))

b = [ i**2 for i in list_number if i%2==0]

print(f'The square of the even numbers are : {b}')

The square of the even numbers are : [0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304]


In [ ]:
# To find the square of even numbers and cube of odd numbers
list_number= list(range(20))

b = [ i**2 if i%2==0 else i**3 for i in list_number ]

print(f'The square of even and cube of odd numbers are : {b}')

The square of even and cube of odd numbers are : [0, 1, 4, 27, 16, 125, 36, 343, 64, 729, 100, 1331, 144, 2197, 196, 3375, 256, 4913, 324, 6859]


In [9]:
# getsizeof()

import sys
a = [1,2,3,4]
print("the size of the list is : " , sys.getsizeof(a))

the size of the list is :  88


In [11]:
import numpy as np

a = np.array([1,2,3,4])
print('The size of the array is : ' , a.itemsize)

The size of the array is :  8


In [ ]:
#                                                          SET COMPREHENSION

In [ ]:
# To find the square of even numbers and cube of odd numbers
set_number= list(range(20))

b = [ i**2 if i%2==0 else i**3 for i in set_number ]

print(f'The square of even and cube of odd numbers are : {b}')

The square of even and cube of odd numbers are : [0, 1, 4, 27, 16, 125, 36, 343, 64, 729, 100, 1331, 144, 2197, 196, 3375, 256, 4913, 324, 6859]


In [ ]:
# To find the first letter of each word
sentence = "Here is a demo sentence for the code."
b = [i[0] for i in sentence.split()]
print(b)

['H', 'i', 'a', 'd', 's', 'f', 't', 'c']


In [ ]:
# To find the first letter of each word
sentence = "Here is a demo ,sentence for the code ."
b = [i[0] for i in sentence.split(',')]
b = [j[0] for j in sentence.split('.')]
print(b)

IndexError: string index out of range

In [ ]:
# Factorial of a number
a = 10
fact = 1
for i in range(1,a+1):
 fact=fact*(i)
print(fact)

3628800


In [ ]:
#                                                             FUNCTIONS

In [ ]:
# def Statement
'''
def function_name(arg1,arg2,...):
  operations
  return
'''


In [ ]:
# Function to create factorial of a number
def fact1(a):
  fact = 1
  for i in range(1,a+1):
    fact=fact*(i)
  print(fact)
  return fact1
fact1(10)

3628800


<function __main__.fact1(a)>

In [ ]:
sample_date = '2020-07-01'
#              year -month-day

a = sample_date.split('-')
print(a)

def month_guess(a):
 b = int(a[1])
 if b in range(1,3) :
  print("1st quarter")
 elif b in range(4,6):
  print("2nd quarter")
 elif b in range(4,6):
  print("3nd quarter")
 elif b in range(4,6):
  print("4nd quarter")

month_guess(a)

['2020', '07', '01']
3nd quarter


In [ ]:
a = [1,2,3,4,5,6]
   #  [1,2,3,100,4,5,6]
value = 100
index1 = 3

# creating another list and extending it to the main list so that the last lement too can be swapped

def func():

 b = [0]
 a.extend(b)

 for i in range(len(a)-1,index1 -1,-1) :
    a[i] = a[i-1]
 a[3]=100

func()

print(a)

[1, 2, 3, 100, 4, 5, 6]


In [ ]:
a = [1,2,3,4,5,6]

def funcc(a):
 value = 100
 index1 = 3
 a = a[:3] + [value] + a[3:6]
 print(a)

funcc(a)



[1, 2, 3, 100, 4, 5, 6]


In [ ]:
#                                                                OOPS

In [ ]:
# CLASS

In [ ]:
class bpit:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def student_name(self):
    print(f"this is class bpit and student name is : {self.name}")

  def student_age(self):
    print(f"this is class bpit and the student age is : {self.age}")


b = bpit("Rahul",20)
b.student_name()
b.student_age()

this is class bpit and student name is : Rahul
this is class bpit and the student age is : 20


In [ ]:
#                                                                EXCEPTION HANDLING

In [ ]:
# except
# except: block (without specifying the error type) catches all exceptions, including those that you might not intend to handle

In [ ]:
a = "rahul"
try:
  print(abc)
except:
  print("hello")

hello


In [ ]:
#                                                                      LIBRARIES

In [ ]:
'''A library in Python is a collection of pre-written code that provides functions, classes, and methods to help with specific tasks.
Libraries help you avoid reinventing the wheel by offering solutions for common problems, such as data manipulation, machine learning, web development, and more.
When you use a library, you can import and utilize its functions and features instead of writing them from scratch.
For example, NumPy and Pandas are libraries for handling arrays, data analysis, and manipulation.'''

In [ ]:
                                                                        # NumPy

In [ ]:
import numpy as np

In [ ]:
# 1D array
a = np.array([1,2,3,4])
type(a)
print(a)
a.shape

[1 2 3 4]


(4,)

In [ ]:
# 2D array
a = np.array([[1,2],[3,4],[5,6]])
type(a)
print(a)

a.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [ ]:
# 3D array
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
type(a)
print(a)

a.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [ ]:
# 4D array
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[1,2],[3,4]],[[1,2],[3,4]]])
type(a)
print(a)

a.shape
#                   4              2             2
#             (sub-arrays)       (rows)      (columns)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


(4, 2, 2)

In [ ]:
# .size -     gives the size of the array

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
(f'The total number of elements in the array is :{a.size}')

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


'The total number of elements in the array is :8'

In [ ]:
# dtype - returns the data type of the array

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.dtype)

int64


In [ ]:
a = np.array([[[1.0 , 2.3],[3,4]],[[5,6],[7,8]]])
print(a.dtype)

float64


In [ ]:
#  in string it returns U(no. of characters of the string)
a = np.array(["abcdefghijklmnopqrstuvwxyz"])
print(a.dtype)

<U26


In [ ]:
# astype - This changes the data type of an array
##########################################################################################################################################################
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.dtype)
a.astype('float64')
print(a)

int64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#                                                   WAYS TO INITIALISE AN ARRAY

In [ ]:
# USING zeros
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# USING ones
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# creting for any number
a = np.ones((3,4))
print(a*30)

[[30. 30. 30. 30.]
 [30. 30. 30. 30.]
 [30. 30. 30. 30.]]


In [ ]:
# array from random numbers using random and randint

a = np.random.randint(10,15,(3,4))
#                    (lower_range , upper_range , ( shape) )
print(a)

[[11 10 13 10]
 [11 14 13 13]
 [11 14 14 14]]


In [ ]:
# slicing 1D array
# a['columns]

In [ ]:
# slicing 2D array
# a[rows,columns]

In [ ]:
# slicing 3D array
# a[sub-arrays,rows,columns]

In [ ]:
a = np.random.randint(10,15,(4,2))
print(a)
print(a[0,0])
print(a[1,0])


[[10 10]
 [11 14]
 [13 12]
 [11 12]]
10
11
10
14


In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a[     1     ,  1  ,  1])
#       (sub-array , row , column)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a[     1     ,  -2  ,  -2])
#       (sub-array , row , column)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
5


In [ ]:
# transpose
print(a)
print(a.T)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [ ]:
# np.reshape(shape) - gives a new shape to the array without changing its data

a = np.random.randint(10,15,(4,3))
print(a)

print(np.reshape(a,(3,4)))




[[12 13 12]
 [14 10 13]
 [11 10 12]
 [13 13 12]]
[[12 13 12 14]
 [10 13 11 10]
 [12 13 13 12]]


In [ ]:
# resize - it adds duplicate values for the indexes where data is not present
a = np.random.randint(10,15,(3,3))
print("before resize")
print(a)
print("after resize")
print(np.resize(a,(2,5,5)))


before resize
[[10 13 12]
 [12 10 13]
 [14 11 14]]
after resize
[[[10 13 12 12 10]
  [13 14 11 14 10]
  [13 12 12 10 13]
  [14 11 14 10 13]
  [12 12 10 13 14]]

 [[11 14 10 13 12]
  [12 10 13 14 11]
  [14 10 13 12 12]
  [10 13 14 11 14]
  [10 13 12 12 10]]]


In [ ]:
# flatten -    converts n-D array into 1-D array
a = np.random.randint(10,15,(3,3))
print("before flatten")
print(a)

print("after flatten")
a.flatten()



before flatten
[[10 11 10]
 [10 13 13]
 [11 10 12]]
after flatten


array([10, 11, 10, 10, 13, 13, 11, 10, 12])

In [ ]:
#                                                                           COPY AND VIEW

In [ ]:
'''View: A view is like a window into the original data. It does NOT create a new copy of the data, but points to the same underlying data in memory.
 So, if you modify the view, the original data also changes.

Copy: A copy creates a new, independent object with the same data. Changes to the copy do NOT affect the original data. '''

In [ ]:
parse_code("John000Doe000123") -> {
    "f_name": "John",
    "l_name": "Doe",
    "id"    : "123"
}

In [ ]:
parse_code = "John000Doe0000123"
def func(parse_code):
  a = parse_code.replace("0", " ")
  a = a.split()
  print(a)
  b = {}
  b["f_name"] = a[0]
  b["l_name"] = a[1]
  b["id"] = a[2]
  print(b)


func(parse_code)

['John', 'Doe', '123']
{'f_name': 'John', 'l_name': 'Doe', 'id': '123'}


In [ ]:
a = np.random.randint(10,15,(3,3))
print(a)
b = np.random.randint(10,15,(3,3))
print(b)
print(a+b)

[[11 14 11]
 [11 11 14]
 [14 10 11]]
[[13 13 13]
 [13 11 12]
 [11 12 10]]
[[24 27 24]
 [24 22 26]
 [25 22 21]]


In [ ]:
a = np.random.randint(10,15,(3,3))
print(a)
print(f'Min value in the array is: {a.min()}')

[[12 14 14]
 [10 12 11]
 [14 11 13]]
Min value in the array is: 10


In [ ]:
a = np.random.randint(10,15,(3,3))
print(a)
print(f'Mean of the array is: {a.mean()}')

[[11 12 10]
 [13 10 11]
 [12 12 11]]
Mean of the array is: 11.333333333333334


In [ ]:
# anagrams - delete the extra elements to make the arrays same

In [ ]:
a = 'cde'
b = 'dcf'
delete = 'ef'
updated_a = 'cd'
updated_b = 'dc'

In [ ]:
a = 'gfrregewrf'
b = 'fsasagrg'
delete = 'reewrfsasa'
updated_a = 'gfrg'
updated_b = 'fggr'

In [ ]:
# a = 'gfrregewrf'
# b = 'fsasagrg'
# delete1 = []
# u_a = []
# u_b = []
# set_a = set(a)
# set_b = set(b)
# for i in a :
#     if i in set_b:
#       u_a.append(i)

#     else :
#           delete1.append(i)

# for j in b :
#     if j in set_b:
#       u_b.append(j)
#     else :
#       delete1.append(j)
#       # b.pop(j)


# print(f'Updated a{u_a}')
# print(f'Updated b{u_b}')
# print(f'Delete {delete1}')









a = 'gfrregewrf'
b = 'fsasagrg'
a = list(a)
b = list(b)
print(a)
print(b)
delete1 = []
u_a = []
u_b = []

# found = true

# Build updated a
# for i in a:
#     if i in b:
#         u_a.append(i)
#     else:
#         delete1.append(i)
#         # a.pop(i)

# Build updated b
# for j in b:
#     if j in u_a:
#         u_b.append(j)
#     else:
#         delete1.append(j)
#         # b.pop(j)

for i in a[:]:
    if i in b:
        u_a.append(i)
        b.remove(i)
        a.pop(a.index(i))
    else:
        delete1.append(i)

# Build updated b
for j in b[:]:
    if j in a:
        u_b.append(j)
        a.remove(j)
        b.pop(b.index(j))
    else:
        delete1.append(j)

print(f'Updated a: {"".join(u_a)}')
print(f'Updated b: {"".join(u_a)}')
print(f'Delete: {"".join(delete1)}')


['g', 'f', 'r', 'r', 'e', 'g', 'e', 'w', 'r', 'f']
['f', 's', 'a', 's', 'a', 'g', 'r', 'g']
Updated a: gfrg
Updated b: gfrg
Delete: reewrfsasa
